In [1]:
import pandas as pd

In [2]:
# Elimina les columnes del dataFrame passades per param

def drop_specific_cols(df, cols):
    df = df.drop(cols,axis=1)
    return df

In [3]:
# csv to df of only 10.000 first songs
msd_df = pd.read_csv('./datasets/msd_reduced.csv', nrows=36000, index_col=0)

In [4]:
# csv to df
grammy_df = pd.read_csv('./datasets/grammy_reduced.csv', index_col=0)
billboard_df = pd.read_csv('./datasets/billboard_reduced.csv', index_col=0)
spotify_df = pd.read_csv('./datasets/spotify_combined.csv', index_col=0)

In [5]:
# inner join between spotify and msd per obtenir els param físics
new_df = pd.merge(msd_df, spotify_df, left_on=['title','artist_name'], right_on = ['title_spoty','all_artists'])
print ("Number of rows matched : %d"%new_df['popularity'].count())
new_df.describe()

Number of rows matched : 16251

,danceability,duration,end_of_fade_in,energy,key,loudness,mode,start_of_fade_out,tempo,time_signature,artist_familiarity,artist_hotttnesss,artist_latitude,artist_longitude,song_hotttnesss,year,popularity,index
count,16251.0,16251.000000,16251.000000,16251.0,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,16250.000000,16251.000000,6191.000000,6191.000000,10178.000000,16251.000000,16251.000000,16251.000000
mean,0.0,241.830750,0.813450,0.0,5.313396,-9.928168,0.679404,232.870017,124.716469,3.593317,0.560623,0.380939,39.073946,-59.706271,0.377213,1197.468648,9.247800,15687.159929
std,0.0,118.431612,1.993506,0.0,3.570588,5.008003,0.466720,116.066885,35.066373,1.203156,0.132129,0.122017,15.136138,54.872404,0.234815,979.500685,13.155059,11516.436096
min,0.0,0.626490,0.000000,0.0,0.000000,-47.403000,0.000000,0.626000,0.000000,0.000000,0.000000,0.000000,-43.531310,-157.719700,0.000000,0.000000,0.000000,2.000000
25%,0.0,179.539140,0.000000,0.0,2.000000,-12.414000,0.000000,171.668500,98.499000,3.000000,0.483984,0.336927,34.053490,-93.264930,0.229144,0.000000,0.000000,6834.500000
50%,0.0,225.488530,0.200000,0.0,5.000000,-8.904000,1.000000,216.317000,121.988000,4.000000,0.559737,0.386161,40.494770,-79.056610,0.405116,1990.000000,3.000000,13625.000000
75%,0.0,279.104850,0.438000,0.0,9.000000,-6.305000,1.000000,269.012000,145.661000,4.000000,0.641086,0.441719,47.603560,-2.591430,0.553610,2004.000000,14.000000,20388.500000
max,0.0,3029.080360,45.697000,0.0,11.000000,3.894000,1.000000,2999.583000,253.887000,7.000000,1.000000,1.082503,70.695760,175.471310,1.000000,2010.000000,81.000000,41589.000000

In [6]:
# left joins for matches between spotify and grammy per obtenir el num de grammy's
new_df = pd.merge(new_df, grammy_df, how='left', left_on=['title','artist_name'], right_on = ['nominee','artist'])
# display matches
print ("Number of rows matched : %d"%new_df['nominee'].count())
new_df.describe()

Number of rows matched : 24

,danceability,duration,end_of_fade_in,energy,key,loudness,mode,start_of_fade_out,tempo,time_signature,artist_familiarity,artist_hotttnesss,artist_latitude,artist_longitude,song_hotttnesss,year,popularity,index,prizes
count,16251.0,16251.000000,16251.000000,16251.0,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,16250.000000,16251.000000,6191.000000,6191.000000,10178.000000,16251.000000,16251.000000,16251.000000,24.000000
mean,0.0,241.830750,0.813450,0.0,5.313396,-9.928168,0.679404,232.870017,124.716469,3.593317,0.560623,0.380939,39.073946,-59.706271,0.377213,1197.468648,9.247800,15687.159929,1.041667
std,0.0,118.431612,1.993506,0.0,3.570588,5.008003,0.466720,116.066885,35.066373,1.203156,0.132129,0.122017,15.136138,54.872404,0.234815,979.500685,13.155059,11516.436096,0.204124
min,0.0,0.626490,0.000000,0.0,0.000000,-47.403000,0.000000,0.626000,0.000000,0.000000,0.000000,0.000000,-43.531310,-157.719700,0.000000,0.000000,0.000000,2.000000,1.000000
25%,0.0,179.539140,0.000000,0.0,2.000000,-12.414000,0.000000,171.668500,98.499000,3.000000,0.483984,0.336927,34.053490,-93.264930,0.229144,0.000000,0.000000,6834.500000,1.000000
50%,0.0,225.488530,0.200000,0.0,5.000000,-8.904000,1.000000,216.317000,121.988000,4.000000,0.559737,0.386161,40.494770,-79.056610,0.405116,1990.000000,3.000000,13625.000000,1.000000
75%,0.0,279.104850,0.438000,0.0,9.000000,-6.305000,1.000000,269.012000,145.661000,4.000000,0.641086,0.441719,47.603560,-2.591430,0.553610,2004.000000,14.000000,20388.500000,1.000000
max,0.0,3029.080360,45.697000,0.0,11.000000,3.894000,1.000000,2999.583000,253.887000,7.000000,1.000000,1.082503,70.695760,175.471310,1.000000,2010.000000,81.000000,41589.000000,2.000000

In [7]:
new_df = pd.merge(new_df, billboard_df, how='left', left_on=['title','artist_name'], right_on = ['song','artist'])
print ("Number of rows matched : %d"%new_df['song'].count())
new_df.describe()

Number of rows matched : 321

,danceability,duration,end_of_fade_in,energy,key,loudness,mode,start_of_fade_out,tempo,time_signature,...,artist_latitude,artist_longitude,song_hotttnesss,year,popularity,index,prizes,rank,peak-rank,weeks-on-board
count,16251.0,16251.000000,16251.000000,16251.0,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,...,6191.000000,6191.000000,10178.000000,16251.000000,16251.000000,16251.000000,24.000000,321.000000,321.000000,321.000000
mean,0.0,241.830750,0.813450,0.0,5.313396,-9.928168,0.679404,232.870017,124.716469,3.593317,...,39.073946,-59.706271,0.377213,1197.468648,9.247800,15687.159929,1.041667,72.595016,35.598131,13.987539
std,0.0,118.431612,1.993506,0.0,3.570588,5.008003,0.466720,116.066885,35.066373,1.203156,...,15.136138,54.872404,0.234815,979.500685,13.155059,11516.436096,0.204124,24.433286,31.237555,8.348643
min,0.0,0.626490,0.000000,0.0,0.000000,-47.403000,0.000000,0.626000,0.000000,0.000000,...,-43.531310,-157.719700,0.000000,0.000000,0.000000,2.000000,1.000000,20.000000,1.000000,1.000000
25%,0.0,179.539140,0.000000,0.0,2.000000,-12.414000,0.000000,171.668500,98.499000,3.000000,...,34.053490,-93.264930,0.229144,0.000000,0.000000,6834.500000,1.000000,48.000000,8.000000,8.000000
50%,0.0,225.488530,0.200000,0.0,5.000000,-8.904000,1.000000,216.317000,121.988000,4.000000,...,40.494770,-79.056610,0.405116,1990.000000,3.000000,13625.000000,1.000000,80.000000,25.000000,13.000000
75%,0.0,279.104850,0.438000,0.0,9.000000,-6.305000,1.000000,269.012000,145.661000,4.000000,...,47.603560,-2.591430,0.553610,2004.000000,14.000000,20388.500000,1.000000,95.000000,63.000000,19.000000
max,0.0,3029.080360,45.697000,0.0,11.000000,3.894000,1.000000,2999.583000,253.887000,7.000000,...,70.695760,175.471310,1.000000,2010.000000,81.000000,41589.000000,2.000000,100.000000,99.000000,54.000000

In [8]:
display(new_df)

,danceability,duration,end_of_fade_in,energy,key,loudness,mode,start_of_fade_out,tempo,time_signature,...,popularity,index,nominee,artist_x,prizes,rank,song,artist_y,peak-rank,weeks-on-board
0,0.0,138.97098,0.000,0.0,7,-2.060,1,138.971,177.768,4,...,11,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,221.20444,0.165,0.0,11,-12.214,0,212.120,98.020,4,...,17,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,318.45832,0.502,0.0,10,-10.670,1,306.265,67.567,3,...,5,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,262.26893,0.194,0.0,11,-3.925,1,259.419,122.332,4,...,5,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,196.02240,0.000,0.0,8,-6.366,1,185.202,189.346,7,...,22,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16246,0.0,196.67546,0.000,0.0,0,-5.117,1,189.098,123.084,3,...,5,22528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16247,0.0,268.53832,3.959,0.0,0,-8.746,1,253.951,118.721,5,...,16,22530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16248,0.0,208.45669,0.000,0.0,9,-15.338,1,190.537,120.720,4,...,8,22532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16249,0.0,228.17914,0.293,0.0,11,-6.728,1,223.742,130.931,1,...,1,22533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16250,0.0,98.76853,0.490,0.0,11,-7.962,1,98.769,196.265,1,...,19,22534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Creem una nova columna, e_grammy, que pren valors binaris 0 o 1 segons si la cançó ha guanyat un Grammy.
# Ojo perquè una cançó pot guanyar més d'un Grammy.
new_df['e_grammy'] = new_df['nominee'].notnull().astype('int')

In [10]:
new_df.describe()

,danceability,duration,end_of_fade_in,energy,key,loudness,mode,start_of_fade_out,tempo,time_signature,...,artist_longitude,song_hotttnesss,year,popularity,index,prizes,rank,peak-rank,weeks-on-board,e_grammy
count,16251.0,16251.000000,16251.000000,16251.0,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,...,6191.000000,10178.000000,16251.000000,16251.000000,16251.000000,24.000000,321.000000,321.000000,321.000000,16251.000000
mean,0.0,241.830750,0.813450,0.0,5.313396,-9.928168,0.679404,232.870017,124.716469,3.593317,...,-59.706271,0.377213,1197.468648,9.247800,15687.159929,1.041667,72.595016,35.598131,13.987539,0.001477
std,0.0,118.431612,1.993506,0.0,3.570588,5.008003,0.466720,116.066885,35.066373,1.203156,...,54.872404,0.234815,979.500685,13.155059,11516.436096,0.204124,24.433286,31.237555,8.348643,0.038402
min,0.0,0.626490,0.000000,0.0,0.000000,-47.403000,0.000000,0.626000,0.000000,0.000000,...,-157.719700,0.000000,0.000000,0.000000,2.000000,1.000000,20.000000,1.000000,1.000000,0.000000
25%,0.0,179.539140,0.000000,0.0,2.000000,-12.414000,0.000000,171.668500,98.499000,3.000000,...,-93.264930,0.229144,0.000000,0.000000,6834.500000,1.000000,48.000000,8.000000,8.000000,0.000000
50%,0.0,225.488530,0.200000,0.0,5.000000,-8.904000,1.000000,216.317000,121.988000,4.000000,...,-79.056610,0.405116,1990.000000,3.000000,13625.000000,1.000000,80.000000,25.000000,13.000000,0.000000
75%,0.0,279.104850,0.438000,0.0,9.000000,-6.305000,1.000000,269.012000,145.661000,4.000000,...,-2.591430,0.553610,2004.000000,14.000000,20388.500000,1.000000,95.000000,63.000000,19.000000,0.000000
max,0.0,3029.080360,45.697000,0.0,11.000000,3.894000,1.000000,2999.583000,253.887000,7.000000,...,175.471310,1.000000,2010.000000,81.000000,41589.000000,2.000000,100.000000,99.000000,54.000000,1.000000

In [11]:
count = (new_df['e_grammy'] != 0).sum()
print(count)

24

In [12]:
#yay!

In [13]:
new_df['is_billboard'] = new_df['peak-rank'].notnull().astype('int')

In [14]:
def billboard_success(m, s, is_billboard):
    if is_billboard:
        return (101 - m + s)
    else:
        return 0

In [15]:
# Per cada fila de la taula new_df, cridem la funció billboard_success amb els atributs seg. i guardem el valor computat a e_billboard
new_df['e_billboard'] = new_df.apply(lambda x: billboard_success(x['peak-rank'], x['weeks-on-board'],x['is_billboard']), axis=1)

In [16]:
display(new_df)

,danceability,duration,end_of_fade_in,energy,key,loudness,mode,start_of_fade_out,tempo,time_signature,...,artist_x,prizes,rank,song,artist_y,peak-rank,weeks-on-board,e_grammy,is_billboard,e_billboard
0,0.0,138.97098,0.000,0.0,7,-2.060,1,138.971,177.768,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0
1,0.0,221.20444,0.165,0.0,11,-12.214,0,212.120,98.020,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0
2,0.0,318.45832,0.502,0.0,10,-10.670,1,306.265,67.567,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0
3,0.0,262.26893,0.194,0.0,11,-3.925,1,259.419,122.332,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0
4,0.0,196.02240,0.000,0.0,8,-6.366,1,185.202,189.346,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16246,0.0,196.67546,0.000,0.0,0,-5.117,1,189.098,123.084,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0
16247,0.0,268.53832,3.959,0.0,0,-8.746,1,253.951,118.721,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0
16248,0.0,208.45669,0.000,0.0,9,-15.338,1,190.537,120.720,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0
16249,0.0,228.17914,0.293,0.0,11,-6.728,1,223.742,130.931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0
16250,0.0,98.76853,0.490,0.0,11,-7.962,1,98.769,196.265,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0

In [17]:
new_df.describe()

,danceability,duration,end_of_fade_in,energy,key,loudness,mode,start_of_fade_out,tempo,time_signature,...,year,popularity,index,prizes,rank,peak-rank,weeks-on-board,e_grammy,is_billboard,e_billboard
count,16251.0,16251.000000,16251.000000,16251.0,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,...,16251.000000,16251.000000,16251.000000,24.000000,321.000000,321.000000,321.000000,16251.000000,16251.000000,16251.000000
mean,0.0,241.830750,0.813450,0.0,5.313396,-9.928168,0.679404,232.870017,124.716469,3.593317,...,1197.468648,9.247800,15687.159929,1.041667,72.595016,35.598131,13.987539,0.001477,0.019753,1.568150
std,0.0,118.431612,1.993506,0.0,3.570588,5.008003,0.466720,116.066885,35.066373,1.203156,...,979.500685,13.155059,11516.436096,0.204124,24.433286,31.237555,8.348643,0.038402,0.139153,12.234954
min,0.0,0.626490,0.000000,0.0,0.000000,-47.403000,0.000000,0.626000,0.000000,0.000000,...,0.000000,0.000000,2.000000,1.000000,20.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,0.0,179.539140,0.000000,0.0,2.000000,-12.414000,0.000000,171.668500,98.499000,3.000000,...,0.000000,0.000000,6834.500000,1.000000,48.000000,8.000000,8.000000,0.000000,0.000000,0.000000
50%,0.0,225.488530,0.200000,0.0,5.000000,-8.904000,1.000000,216.317000,121.988000,4.000000,...,1990.000000,3.000000,13625.000000,1.000000,80.000000,25.000000,13.000000,0.000000,0.000000,0.000000
75%,0.0,279.104850,0.438000,0.0,9.000000,-6.305000,1.000000,269.012000,145.661000,4.000000,...,2004.000000,14.000000,20388.500000,1.000000,95.000000,63.000000,19.000000,0.000000,0.000000,0.000000
max,0.0,3029.080360,45.697000,0.0,11.000000,3.894000,1.000000,2999.583000,253.887000,7.000000,...,2010.000000,81.000000,41589.000000,2.000000,100.000000,99.000000,54.000000,1.000000,1.000000,153.000000

In [18]:
count_b = (new_df['e_billboard'] != 0).sum()
print(count_b)

321

In [19]:
new_df['popularity'] = new_df['popularity'].fillna(0)
new_df['e_spotify'] = 0
new_df.loc[new_df['popularity'] >= new_df['popularity'].quantile(0.75), 'e_spotify'] = 1
new_df.loc[new_df['popularity'] < new_df['popularity'].quantile(0.75), 'e_spotify'] = 0

In [20]:
count_s = (new_df['e_spotify'] != 0).sum()
print(count_s)

4146

In [21]:
# Eliminem columnes innecessàries per a estudiar les dades
cols = [ 'nominee', 'artist_x', 'rank', 'song', 'artist_y', 'peak-rank', 'weeks-on-board', 'is_billboard', 'all_artists', 'popularity', 'prizes', 'index']
new_df = drop_specific_cols(new_df, cols)

In [22]:
display(new_df)

,danceability,duration,end_of_fade_in,energy,key,loudness,mode,start_of_fade_out,tempo,time_signature,...,artist_location,artist_longitude,artist_name,release,song_hotttnesss,title,year,e_grammy,e_billboard,e_spotify
0,0.0,138.97098,0.000,0.0,7,-2.060,1,138.971,177.768,4,...,"Glasgow, Scotland",-4.24251,Hudson Mohawke,Butter,0.617871,No One Could Ever,2006,0,0.0,0
1,0.0,221.20444,0.165,0.0,11,-12.214,0,212.120,98.020,4,...,NaN,NaN,Kris Kross,Da Bomb,NaN,2 Da Beat Ch'yall,1993,0,0.0,1
2,0.0,318.45832,0.502,0.0,10,-10.670,1,306.265,67.567,3,...,NaN,NaN,Tiger Lou,The Loyal,0.463490,Pilots,2005,0,0.0,0
3,0.0,262.26893,0.194,0.0,11,-3.925,1,259.419,122.332,4,...,"Vetlanda, Sweden",15.08518,Lena Philipsson,Lena 20 År,0.212045,006,1998,0,0.0,0
4,0.0,196.02240,0.000,0.0,8,-6.366,1,185.202,189.346,7,...,Maryland,-75.92381,Dying Fetus,Descend Into Depravity,0.614766,Ethos of Coercion,2009,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16246,0.0,196.67546,0.000,0.0,0,-5.117,1,189.098,123.084,3,...,NaN,NaN,Ace Troubleshooter,Ace Troubleshooter,NaN,Don't Trust That Girl,1999,0,0.0,0
16247,0.0,268.53832,3.959,0.0,0,-8.746,1,253.951,118.721,5,...,NaN,NaN,Baaba Maal,Missing You (Mi Yeewnii),NaN,Jamma - Jenngii,2001,0,0.0,1
16248,0.0,208.45669,0.000,0.0,9,-15.338,1,190.537,120.720,4,...,"Tromso, Norway",NaN,Biosphere,Microgravity,0.530026,Chromosphere,1991,0,0.0,0
16249,0.0,228.17914,0.293,0.0,11,-6.728,1,223.742,130.931,1,...,Florida,NaN,Root,Zjeveni/The Temple In The Underworld,0.430161,Hrbitov,0,0,0.0,0
16250,0.0,98.76853,0.490,0.0,11,-7.962,1,98.769,196.265,1,...,"Santa Barbara, CA",NaN,Lagwagon,Duh,0.537612,Noble End,1992,0,0.0,1

In [23]:
new_df.describe()

,danceability,duration,end_of_fade_in,energy,key,loudness,mode,start_of_fade_out,tempo,time_signature,artist_familiarity,artist_hotttnesss,artist_latitude,artist_longitude,song_hotttnesss,year,e_grammy,e_billboard,e_spotify
count,16251.0,16251.000000,16251.000000,16251.0,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,16251.000000,16250.000000,16251.000000,6191.000000,6191.000000,10178.000000,16251.000000,16251.000000,16251.000000,16251.000000
mean,0.0,241.830750,0.813450,0.0,5.313396,-9.928168,0.679404,232.870017,124.716469,3.593317,0.560623,0.380939,39.073946,-59.706271,0.377213,1197.468648,0.001477,1.568150,0.255123
std,0.0,118.431612,1.993506,0.0,3.570588,5.008003,0.466720,116.066885,35.066373,1.203156,0.132129,0.122017,15.136138,54.872404,0.234815,979.500685,0.038402,12.234954,0.435944
min,0.0,0.626490,0.000000,0.0,0.000000,-47.403000,0.000000,0.626000,0.000000,0.000000,0.000000,0.000000,-43.531310,-157.719700,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.0,179.539140,0.000000,0.0,2.000000,-12.414000,0.000000,171.668500,98.499000,3.000000,0.483984,0.336927,34.053490,-93.264930,0.229144,0.000000,0.000000,0.000000,0.000000
50%,0.0,225.488530,0.200000,0.0,5.000000,-8.904000,1.000000,216.317000,121.988000,4.000000,0.559737,0.386161,40.494770,-79.056610,0.405116,1990.000000,0.000000,0.000000,0.000000
75%,0.0,279.104850,0.438000,0.0,9.000000,-6.305000,1.000000,269.012000,145.661000,4.000000,0.641086,0.441719,47.603560,-2.591430,0.553610,2004.000000,0.000000,0.000000,1.000000
max,0.0,3029.080360,45.697000,0.0,11.000000,3.894000,1.000000,2999.583000,253.887000,7.000000,1.000000,1.082503,70.695760,175.471310,1.000000,2010.000000,1.000000,153.000000,1.000000

In [24]:
# export to csv file
new_df.to_csv("successes55000_with_spotify.csv")